import { useEffect, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Save, Settings, ShieldCheck } from "lucide-react";

type SettingsMap = Record<string, unknown>;

export const Route = createFileRoute("/admin/configuracoes")({ component: SettingsPage });

const defaults: SettingsMap = { whatsapp: "", email: "", businessHours: "Segunda a sexta, 8h às 18h", publicFinancing: true, leadSources: ["site", "whatsapp", "instagram", "indicação"], adminResponsible: "" };

function SettingsPage() {
  const [settings, setSettings] = useState<SettingsMap>(defaults);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  useEffect(() => { fetch("/admin/settings/api", { headers: { Accept: "application/json" } }).then(async (r) => { const value = await r.json() as { settings?: SettingsMap; error?: string }; if (!r.ok) throw new Error(value.error ?? "Não foi possível carregar as configurações."); setSettings({ ...defaults, ...(value.settings ?? {}) }); }).catch((e) => setMessage(e instanceof Error ? e.message : "Não foi possível carregar as configurações.")).finally(() => setLoading(false)); }, []);
  const set = (key: string, value: unknown) => setSettings((current) => ({ ...current, [key]: value }));
  const save = async () => { setSaving(true); setMessage(""); try { const response = await fetch("/admin/settings/api", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ settings }) }); const result = await response.json() as { ok?: boolean; error?: string }; if (!response.ok || !result.ok) throw new Error(result.error ?? "Não foi possível salvar."); setMessage("Configurações salvas com sucesso."); } catch (e) { setMessage(e instanceof Error ? e.message : "Não foi possível salvar."); } finally { setSaving(false); } };
  if (loading) return <Shell><Panel>Carregando configurações…</Panel></Shell>;
  return <Shell><div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-[0.18em] text-gold">Painel administrativo</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Configurações comerciais</h1><p className="mt-2 text-sm text-muted-foreground">Parâmetros centrais usados pela operação da Gomes Motors.</p></header>{message && <Panel><p className="text-sm">{message}</p></Panel>}<Panel><div className="grid gap-5 sm:grid-cols-2"><Field label="WhatsApp comercial" value={String(settings.whatsapp ?? "")} onChange={(v) => set("whatsapp", v)} placeholder="5522999999999" /><Field label="E-mail comercial" value={String(settings.email ?? "")} onChange={(v) => set("email", v)} placeholder="contato@exemplo.com" /><Field label="Responsável padrão" value={String(settings.adminResponsible ?? "")} onChange={(v) => set("adminResponsible", v)} placeholder="Nome do responsável" /><Field label="Horário de atendimento" value={String(settings.businessHours ?? "")} onChange={(v) => set("businessHours", v)} placeholder="Segunda a sexta, 8h às 18h" /><label className="flex items-center gap-3 rounded-sm border border-border bg-secondary/50 p-4 sm:col-span-2"><input type="checkbox" checked={Boolean(settings.publicFinancing)} onChange={(e) => set("publicFinancing", e.target.checked)} className="h-4 w-4" /><span><strong className="block text-sm">Simulador público de financiamento</strong><span className="text-xs text-muted-foreground">Permite que o site continue exibindo a simulação educativa.</span></span></label><label className="block sm:col-span-2"><span className="mb-1.5 block text-xs font-bold uppercase tracking-wider text-muted-foreground">Origens de lead</span><input value={Array.isArray(settings.leadSources) ? settings.leadSources.join(", ") : ""} onChange={(e) => set("leadSources", e.target.value.split(",").map((v) => v.trim()).filter(Boolean))} className="w-full rounded-sm border border-border bg-secondary px-3 py-2.5 text-sm outline-none focus:border-gold" /><span className="mt-1 block text-xs text-muted-foreground">Separe cada origem por vírgula.</span></label></div><button disabled={saving} onClick={() => void save()} className="mt-6 inline-flex items-center gap-2 rounded-sm bg-foreground px-4 py-2.5 text-sm font-semibold text-background disabled:opacity-50"><Save className="h-4 w-4" />{saving ? "Salvando…" : "Salvar configurações"}</button></Panel></div></Shell>;
}
function Shell({ children }: { children: React.ReactNode }) { return <div className="min-h-[calc(100vh-120px)] bg-background"><div className="mx-auto max-w-5xl px-4 py-6 sm:px-6 lg:px-8"><div className="mb-6 flex items-center justify-between"><Link to="/admin" className="inline-flex items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" />Painel administrativo</Link><div className="flex h-10 w-10 items-center justify-center rounded-sm bg-gold/10 text-gold"><Settings className="h-5 w-5" /></div></div>{children}</div></div>; }
function Panel({ children }: { children: React.ReactNode }) { return <section className="rounded-sm border border-border bg-card p-5 sm:p-6">{children}</section>; }
function Field({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string }) { return <label className="block"><span className="mb-1.5 block text-xs font-bold uppercase tracking-wider text-muted-foreground">{label}</span><input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-sm border border-border bg-secondary px-3 py-2.5 text-sm outline-none focus:border-gold" /></label>; }
