import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Plus, RefreshCw, Save } from "lucide-react";
import { Link, createFileRoute } from "@tanstack/react-router";

type Row = { id?: unknown; [key: string]: unknown };
type Lead = { id: string; customer_name: string; customer_phone?: string | null; intent: string; status: string };
type Vehicle = { id: string; brand: string; model: string; version?: string | null; status: string; price_cents: number };
type Data = { evaluations: Row[]; negotiations: Row[]; reservations: Row[]; sales: Row[]; financing: Row[]; leads: Lead[]; vehicles: Vehicle[] };
type FormState = { customerName?: string; vehicleDescription?: string; leadId?: string; customerPhone?: string; plate?: string; year?: string; mileage?: string; condition?: string; requestedValue?: string; assignedTo?: string; notes?: string; vehicleId?: string; stage?: string; proposedPrice?: string; tradeInValue?: string; downPayment?: string; finalPrice?: string; reservedUntil?: string; responsible?: string; financingOperationId?: string; source?: string; entry?: string; termMonths?: string; ratePercent?: string; institution?: string; estimatedInstallment?: string; proposalReference?: string; status?: string };
type FormKey = keyof FormState;

const labels: Record<string, string> = { pendente: "Pendente", aprovada: "Aprovada", recusada: "Recusada", convertida: "Convertida", aberta: "Aberta", proposta: "Proposta", contraproposta: "Contraproposta", fechada: "Fechada", perdida: "Perdida", ativa: "Ativa", liberada: "Liberada", expirada: "Expirada", cancelada: "Cancelada", simulacao_interna: "Simulação interna", em_analise: "Em análise", aprovado: "Aprovado", recusado: "Recusado", contratado: "Contratado", novo: "Novo", contato: "Contato" };
const money = (value: unknown) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value ?? 0) / 100);
const brlToCents = (value: string | undefined) => { const raw = (value ?? "").trim().replace(/\s/g, ""); if (!raw) return undefined; const normalized = raw.includes(",") ? raw.replace(/\./g, "").replace(",", ".") : raw; const number = Number(normalized); return Number.isFinite(number) && number >= 0 ? Math.round(number * 100) : undefined; };

export const Route = createFileRoute("/admin/operacao")({ component: OperationPage });

function OperationPage() {
  const [data, setData] = useState<Data | null>(null); const [tab, setTab] = useState("avaliacoes"); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [form, setForm] = useState<FormState>({});
  const load = async () => { setLoading(true); try { const response = await fetch("/admin/commercial/api", { headers: { Accept: "application/json" } }); const result = await response.json() as Data & { error?: string }; if (!response.ok) throw new Error(result.error ?? "Falha ao carregar a operação."); setData(result); } catch (error) { setMessage(error instanceof Error ? error.message : "Falha ao carregar a operação."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const counts = useMemo(() => ({ avaliacoes: data?.evaluations.length ?? 0, negociacoes: data?.negotiations.length ?? 0, reservas: data?.reservations.length ?? 0, vendas: data?.sales.length ?? 0, financiamento: data?.financing.length ?? 0 }), [data]);
  const tabs = [["avaliacoes", "Avaliações"], ["negociacoes", "Negociações"], ["reservas", "Reservas"], ["vendas", "Vendas"], ["financiamento", "Financiamento"]] as const;
  const setField = (key: FormKey, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const changeTab = (value: string) => { setTab(value); setForm({}); setMessage(""); };
  const submit = async () => {
    setSaving(true); setMessage("");
    try {
      let action: string; let payload: Record<string, unknown>;
      if (tab === "avaliacoes") { action = "evaluation.create"; payload = { customerName: form.customerName, vehicleDescription: form.vehicleDescription, leadId: form.leadId || undefined, customerPhone: form.customerPhone, plate: form.plate, year: form.year || undefined, mileage: form.mileage || undefined, condition: form.condition, requestedValueCents: brlToCents(form.requestedValue), assignedTo: form.assignedTo, notes: form.notes }; }
      else if (tab === "negociacoes") { action = "negotiation.create"; payload = { leadId: form.leadId, vehicleId: form.vehicleId, stage: form.stage || "aberta", proposedPriceCents: brlToCents(form.proposedPrice), tradeInValueCents: brlToCents(form.tradeInValue), downPaymentCents: brlToCents(form.downPayment), finalPriceCents: brlToCents(form.finalPrice), assignedTo: form.assignedTo, notes: form.notes }; }
      else if (tab === "reservas") { action = "reservation.create"; payload = { leadId: form.leadId || undefined, vehicleId: form.vehicleId, reservedUntil: form.reservedUntil, responsible: form.responsible, notes: form.notes }; }
      else if (tab === "vendas") { action = "sale.create"; payload = { leadId: form.leadId || undefined, vehicleId: form.vehicleId, customerName: form.customerName, finalPriceCents: brlToCents(form.finalPrice), downPaymentCents: brlToCents(form.downPayment), tradeInValueCents: brlToCents(form.tradeInValue), financingOperationId: form.financingOperationId, source: form.source, responsible: form.responsible, notes: form.notes }; }
      else { action = "financing.create"; payload = { leadId: form.leadId || undefined, vehicleId: form.vehicleId || undefined, customerName: form.customerName, entryCents: brlToCents(form.entry), termMonths: form.termMonths || undefined, ratePercent: form.ratePercent || "0", institution: form.institution, estimatedInstallmentCents: brlToCents(form.estimatedInstallment), proposalReference: form.proposalReference, status: form.status || "simulacao_interna", notes: form.notes }; }
      const response = await fetch("/admin/commercial/api", { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify({ action, data: payload }) });
      const result = await response.json() as { ok?: boolean; error?: string }; if (!response.ok || !result.ok) throw new Error(result.error ?? "Operação não concluída."); setMessage("Registro criado com sucesso."); setForm({}); await load();
    } catch (error) { setMessage(error instanceof Error ? error.message : "Operação não concluída."); } finally { setSaving(false); }
  };
  return <main className="min-h-[calc(100vh-120px)] bg-background"><div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-gold">Operação comercial</p><h1 className="mt-1 text-3xl font-bold">Central de operação</h1><p className="mt-2 text-sm text-muted-foreground">Avaliações, negociações, reservas, vendas e financiamento real.</p></div><div className="flex gap-2"><button onClick={() => void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-sm border border-border px-4 py-2.5 text-sm font-semibold hover:bg-accent"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />Atualizar</button><Link to="/admin/crm" className="inline-flex items-center gap-2 rounded-sm border border-border px-4 py-2.5 text-sm font-semibold hover:bg-accent"><ArrowLeft className="h-4 w-4" />CRM</Link></div></div>{message && <div className="mt-5 rounded-sm border border-border bg-card px-4 py-3 text-sm">{message}</div>}<div className="mt-6 grid gap-2 sm:grid-cols-5">{tabs.map(([key, label]) => <button key={key} onClick={() => changeTab(key)} className={`rounded-sm border px-3 py-3 text-left text-sm font-semibold ${tab === key ? "border-gold bg-secondary" : "border-border bg-card hover:bg-accent"}`}><span>{label}</span><span className="ml-2 text-muted-foreground">{counts[key]}</span></button>)}</div><CreateForm tab={tab} form={form} setField={setField} data={data} saving={saving} onSubmit={() => void submit()} /><section className="mt-5 rounded-sm border border-border bg-card p-5">{loading && !data ? <div className="py-16 text-center text-sm text-muted-foreground">Carregando operação…</div> : tab === "avaliacoes" ? <Evaluations rows={data?.evaluations ?? []} /> : tab === "negociacoes" ? <Negotiations rows={data?.negotiations ?? []} /> : tab === "reservas" ? <Reservations rows={data?.reservations ?? []} /> : tab === "vendas" ? <Sales rows={data?.sales ?? []} /> : <Financing rows={data?.financing ?? []} />}</section></div></main>;
}

function CreateForm({ tab, form, setField, data, saving, onSubmit }: { tab: string; form: FormState; setField: (key: FormKey, value: string) => void; data: Data | null; saving: boolean; onSubmit: () => void }) {
  const leads = data?.leads ?? []; const vehicles = data?.vehicles ?? [];
  const leadSelect = <Field label="Lead"><select value={form.leadId ?? ""} onChange={(e) => setField("leadId", e.target.value)} className={inputClass}><option value="">Selecione um lead</option>{leads.map((lead) => <option key={lead.id} value={lead.id}>{lead.customer_name}{lead.customer_phone ? ` · ${lead.customer_phone}` : ""}</option>)}</select></Field>;
  const vehicleSelect = <Field label="Veículo"><select value={form.vehicleId ?? ""} onChange={(e) => setField("vehicleId", e.target.value)} className={inputClass}><option value="">Selecione um veículo</option>{vehicles.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.brand} {vehicle.model}{vehicle.version ? ` ${vehicle.version}` : ""} · {labels[vehicle.status] ?? vehicle.status}</option>)}</select></Field>;
  const textField = (key: FormKey, label: string, placeholder = "") => <Field label={label}><input value={form[key] ?? ""} onChange={(e) => setField(key, e.target.value)} placeholder={placeholder} className={inputClass} /></Field>;
  const moneyField = (key: FormKey, label: string) => textField(key, label, "0,00");
  return <section className="mt-5 rounded-sm border border-border bg-card p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-bold">Novo registro</h2><p className="mt-1 text-xs text-muted-foreground">Preencha os dados para criar uma operação no D1.</p></div><Plus className="h-5 w-5 text-gold" /></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
    {tab === "avaliacoes" && <>{textField("customerName", "Cliente", "Nome completo")}{textField("vehicleDescription", "Veículo avaliado", "Ex.: Honda Civic 2.0")}{leadSelect}{textField("customerPhone", "Telefone")}{textField("plate", "Placa")}{textField("year", "Ano", "2026")}{textField("mileage", "Quilometragem")}{textField("condition", "Condição", "Bom estado")}{moneyField("requestedValue", "Valor solicitado")}{textField("assignedTo", "Responsável")}</>}
    {tab === "negociacoes" && <>{leadSelect}{vehicleSelect}<Field label="Etapa"><select value={form.stage ?? "aberta"} onChange={(e) => setField("stage", e.target.value)} className={inputClass}><option value="aberta">Aberta</option><option value="proposta">Proposta</option><option value="contraproposta">Contraproposta</option><option value="fechada">Fechada</option><option value="perdida">Perdida</option></select></Field>{moneyField("proposedPrice", "Preço proposto")}{moneyField("tradeInValue", "Valor de troca")}{moneyField("downPayment", "Entrada")}{moneyField("finalPrice", "Preço final")}{textField("assignedTo", "Responsável")}</>}
    {tab === "reservas" && <>{leadSelect}{vehicleSelect}{textField("reservedUntil", "Reservado até", "2026-09-10T18:00")}{textField("responsible", "Responsável")}</>}
    {tab === "vendas" && <>{leadSelect}{vehicleSelect}{textField("customerName", "Cliente", "Nome completo")}{moneyField("finalPrice", "Preço final")}{moneyField("downPayment", "Entrada")}{moneyField("tradeInValue", "Valor de troca")}{textField("financingOperationId", "ID do financiamento")}{textField("source", "Origem", "site")}{textField("responsible", "Responsável")}</>}
    {tab === "financiamento" && <>{leadSelect}{vehicleSelect}{textField("customerName", "Cliente", "Nome completo")}{moneyField("entry", "Entrada")}{textField("termMonths", "Prazo (meses)", "48")}{textField("ratePercent", "Taxa mensal (%)", "1,49")}{textField("institution", "Instituição")}{moneyField("estimatedInstallment", "Parcela estimada")}{textField("proposalReference", "Referência da proposta")}{<Field label="Status"><select value={form.status ?? "simulacao_interna"} onChange={(e) => setField("status", e.target.value)} className={inputClass}><option value="simulacao_interna">Simulação interna</option><option value="em_analise">Em análise</option><option value="proposta">Proposta</option><option value="aprovado">Aprovado</option><option value="recusado">Recusado</option><option value="contratado">Contratado</option><option value="cancelado">Cancelado</option></select></Field>}</>}
  </div><div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Observações"><textarea value={form.notes ?? ""} onChange={(e) => setField("notes", e.target.value)} rows={3} className={inputClass} /></Field><div className="flex items-end"><button onClick={onSubmit} disabled={saving} className="inline-flex w-full items-center justify-center gap-2 rounded-sm bg-gold px-4 py-2.5 text-sm font-bold text-black disabled:opacity-50"><Save className="h-4 w-4" />{saving ? "Salvando…" : "Criar registro"}</button></div></div></section>;
}

const inputClass = "w-full rounded-sm border border-border bg-secondary px-3 py-2.5 text-sm outline-none focus:border-gold";
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-muted-foreground">{label}</span>{children}</label>; }
function Empty() { return <div className="py-12 text-center text-sm text-muted-foreground">Nenhum registro encontrado.</div>; }
function Evaluations({ rows }: { rows: Row[] }) { return <Table title="Avaliações de veículos" columns={[["customer_name", "Cliente"], ["vehicle_description", "Veículo"], ["decision", "Decisão"], ["evaluated_value_cents", "Valor avaliado"]]} rows={rows} />; }
function Negotiations({ rows }: { rows: Row[] }) { return <Table title="Negociações" columns={[["customer_name", "Cliente"], ["brand", "Veículo"], ["stage", "Etapa"], ["proposed_price_cents", "Preço proposto"]]} rows={rows} />; }
function Reservations({ rows }: { rows: Row[] }) { return <Table title="Reservas" columns={[["customer_name", "Cliente"], ["brand", "Veículo"], ["status", "Status"], ["reserved_until", "Reservado até"]]} rows={rows} />; }
function Sales({ rows }: { rows: Row[] }) { return <Table title="Vendas" columns={[["customer_name", "Cliente"], ["brand", "Veículo"], ["final_price_cents", "Valor final"], ["sold_at", "Data"]]} rows={rows} />; }
function Financing({ rows }: { rows: Row[] }) { return <Table title="Operações de financiamento" columns={[["customer_name", "Cliente"], ["brand", "Veículo"], ["status", "Status"], ["term_months", "Prazo"], ["estimated_installment_cents", "Parcela"]]} rows={rows} />; }
function Table({ title, columns, rows }: { title: string; columns: [string, string][]; rows: Row[] }) { return <div><div className="flex items-center justify-between"><h2 className="text-lg font-bold">{title}</h2><span className="text-xs text-muted-foreground">{rows.length} registro(s)</span></div>{rows.length === 0 ? <Empty /> : <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-border text-xs uppercase tracking-wider text-muted-foreground"><tr>{columns.map(([, label]) => <th key={label} className="pb-3 pr-5">{label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={String(row.id ?? index)} className="border-b border-border/70"><td className="py-3 pr-5 font-semibold">{String(row[columns[0][0]] ?? "—")}</td>{columns.slice(1).map(([key]) => <td key={key} className="py-3 pr-5 text-muted-foreground">{key.endsWith("_cents") ? money(row[key]) : key === "decision" || key === "stage" || key === "status" ? labels[String(row[key])] ?? String(row[key] ?? "—") : key.endsWith("_at") ? new Date(String(row[key])).toLocaleString("pt-BR") : String(row[key] ?? "—")}</td>)}</tr>)}</tbody></table></div>}</div>; }
