import { env } from "cloudflare:workers";
import { createFileRoute } from "@tanstack/react-router";
import type { D1DatabaseLike } from "@/infrastructure/repositories/d1/d1-types";
import { exceedsBodyLimit, hasAcceptableJsonContentType, isSameOriginRequest } from "@/lib/server-security";

type RuntimeEnv = { DB: D1DatabaseLike };
type CommercialData = Record<string, unknown> & { customerName?: unknown; vehicleDescription?: unknown; leadId?: unknown; customerPhone?: unknown; plate?: unknown; year?: unknown; mileage?: unknown; condition?: unknown; requestedValueCents?: unknown; evaluatedValueCents?: unknown; decision?: unknown; assignedTo?: unknown; notes?: unknown; vehicleId?: unknown; stage?: unknown; proposedPriceCents?: unknown; tradeInValueCents?: unknown; downPaymentCents?: unknown; finalPriceCents?: unknown; reservedUntil?: unknown; responsible?: unknown; status?: unknown; financingOperationId?: unknown; source?: unknown; termMonths?: unknown; entryCents?: unknown; ratePercent?: unknown; institution?: unknown; estimatedInstallmentCents?: unknown; proposalReference?: unknown };
type Action =
  | { action: "evaluation.create"; data: CommercialData }
  | { action: "evaluation.update"; id: string; data: CommercialData }
  | { action: "negotiation.create"; data: CommercialData }
  | { action: "negotiation.update"; id: string; data: CommercialData }
  | { action: "reservation.create"; data: CommercialData }
  | { action: "reservation.update"; id: string; data: CommercialData }
  | { action: "sale.create"; data: CommercialData }
  | { action: "financing.create"; data: CommercialData }
  | { action: "financing.update"; id: string; data: CommercialData };

const database = () => (env as unknown as RuntimeEnv).DB;
const actor = (request: Request) => request.headers.get("cf-access-authenticated-user-email") ?? "cloudflare-access";
const authorized = (request: Request) => Boolean(request.headers.get("cf-access-authenticated-user-email"));
const json = (data: unknown, status = 200) => Response.json(data, { status, headers: { "Cache-Control": "no-store" } });
const text = (value: unknown, field: string, required = false, max = 2000) => { const result = String(value ?? "").trim(); if (required && !result) throw new Error(`${field} é obrigatório.`); if (result.length > max) throw new Error(`${field} excede o limite permitido.`); return result || null; };
const cents = (value: unknown, field: string, required = false) => { if (value === undefined || value === null || value === "") { if (required) throw new Error(`${field} é obrigatório.`); return null; } const n = Number(value); if (!Number.isInteger(n) || n < 0) throw new Error(`${field} inválido.`); return n; };
const integer = (value: unknown, field: string, minimum = 0, required = false) => { if (value === undefined || value === null || value === "") { if (required) throw new Error(`${field} é obrigatório.`); return null; } const n = Number(value); if (!Number.isInteger(n) || n < minimum) throw new Error(`${field} inválido.`); return n; };

async function audit(db: D1DatabaseLike, request: Request, action: string, entityType: string, entityId: string | null, metadata: Record<string, unknown> = {}) { await db.prepare(`INSERT INTO audit_logs (id, actor_id, action, entity_type, entity_id, result, occurred_at, metadata_json) VALUES (?, ?, ?, ?, ?, 'success', ?, ?)`).bind(crypto.randomUUID(), actor(request), action, entityType, entityId, new Date().toISOString(), JSON.stringify(metadata)).run(); }
async function vehicleExists(db: D1DatabaseLike, id: string | null, required = false) { if (!id) { if (required) throw new Error("Veículo é obrigatório."); return; } const row = await db.prepare(`SELECT id FROM vehicles WHERE id = ? LIMIT 1`).bind(id).first<{ id: string }>(); if (!row) throw new Error("Veículo não encontrado."); }
async function leadExists(db: D1DatabaseLike, id: string | null) { if (!id) return; const row = await db.prepare(`SELECT id FROM leads WHERE id = ? LIMIT 1`).bind(id).first<{ id: string }>(); if (!row) throw new Error("Lead não encontrado."); }

async function createEvaluation(db: D1DatabaseLike, request: Request, data: CommercialData) { const customerName = text(data.customerName, "Nome do cliente", true); const vehicleDescription = text(data.vehicleDescription, "Descrição do veículo", true); const leadId = text(data.leadId, "Lead"); await leadExists(db, leadId); const id = crypto.randomUUID(); const now = new Date().toISOString(); await db.prepare(`INSERT INTO vehicle_evaluations (id, lead_id, customer_name, customer_phone, vehicle_description, plate, year, mileage, condition, requested_value_cents, decision, assigned_to, notes, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).bind(id, leadId, customerName, text(data.customerPhone, "Telefone", false, 40), vehicleDescription, text(data.plate, "Placa", false, 20), integer(data.year, "Ano", 1900), integer(data.mileage, "Quilometragem"), text(data.condition, "Condição", false, 5000), cents(data.requestedValueCents, "Valor solicitado"), "pendente", text(data.assignedTo, "Responsável", false, 200), text(data.notes, "Observações"), now, now).run(); await audit(db, request, "evaluation.create", "evaluation", id); return id; }
async function updateEvaluation(db: D1DatabaseLike, request: Request, id: string, data: CommercialData) { const allowed = new Set(["evaluated_value_cents", "decision", "assigned_to", "notes", "condition"]); const values: unknown[] = []; const sets: string[] = []; const mapping: Record<string, string> = { evaluatedValueCents: "evaluated_value_cents", decision: "decision", assignedTo: "assigned_to", notes: "notes", condition: "condition" }; for (const [inputKey, column] of Object.entries(mapping)) if (inputKey in data && allowed.has(column)) { if (column === "decision" && !new Set(["pendente", "aprovada", "recusada", "convertida"]).has(String(data[inputKey]))) throw new Error("Decisão de avaliação inválida."); values.push(column === "evaluated_value_cents" ? cents(data[inputKey], "Valor avaliado") : text(data[inputKey], inputKey, false, 5000)); sets.push(`${column} = ?`); } if (!sets.length) throw new Error("Nenhum campo de avaliação foi informado."); values.push(new Date().toISOString(), id); await db.prepare(`UPDATE vehicle_evaluations SET ${sets.join(", ")}, updated_at = ? WHERE id = ?`).bind(...values).run(); await audit(db, request, "evaluation.update", "evaluation", id, { fields: sets }); }
async function createNegotiation(db: D1DatabaseLike, request: Request, data: CommercialData) { const leadId = text(data.leadId, "Lead"); const vehicleId = text(data.vehicleId, "Veículo"); await leadExists(db, leadId); await vehicleExists(db, vehicleId); const id = crypto.randomUUID(); const now = new Date().toISOString(); const stage = text(data.stage, "Etapa") ?? "aberta"; if (!new Set(["aberta", "proposta", "contraproposta", "fechada", "perdida"]).has(stage)) throw new Error("Etapa de negociação inválida."); await db.prepare(`INSERT INTO negotiations (id, lead_id, vehicle_id, stage, proposed_price_cents, trade_in_value_cents, down_payment_cents, final_price_cents, notes, assigned_to, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).bind(id, leadId, vehicleId, stage, cents(data.proposedPriceCents, "Preço proposto"), cents(data.tradeInValueCents, "Valor de troca"), cents(data.downPaymentCents, "Entrada"), cents(data.finalPriceCents, "Preço final"), text(data.notes, "Observações"), text(data.assignedTo, "Responsável", false, 200), now, now).run(); await audit(db, request, "negotiation.create", "negotiation", id); return id; }
async function updateNegotiation(db: D1DatabaseLike, request: Request, id: string, data: CommercialData) { const mapping: Record<string, string> = { stage: "stage", proposedPriceCents: "proposed_price_cents", tradeInValueCents: "trade_in_value_cents", downPaymentCents: "down_payment_cents", finalPriceCents: "final_price_cents", notes: "notes", assignedTo: "assigned_to" }; const sets: string[] = []; const values: unknown[] = []; for (const [key, column] of Object.entries(mapping)) if (key in data) { if (column === "stage" && !new Set(["aberta", "proposta", "contraproposta", "fechada", "perdida"]).has(String(data[key]))) throw new Error("Etapa de negociação inválida."); values.push(column.endsWith("_cents") ? cents(data[key], key) : text(data[key], key, false, 5000)); sets.push(`${column} = ?`); } if (!sets.length) throw new Error("Nenhum campo de negociação foi informado."); values.push(new Date().toISOString(), id); await db.prepare(`UPDATE negotiations SET ${sets.join(", ")}, updated_at = ? WHERE id = ?`).bind(...values).run(); await audit(db, request, "negotiation.update", "negotiation", id, { fields: sets }); }
async function createReservation(db: D1DatabaseLike, request: Request, data: CommercialData) { const vehicleId = text(data.vehicleId, "Veículo", true); await vehicleExists(db, vehicleId, true); const leadId = text(data.leadId, "Lead"); await leadExists(db, leadId); const active = await db.prepare(`SELECT id FROM reservations WHERE vehicle_id = ? AND status = 'ativa' LIMIT 1`).bind(vehicleId).first<{ id: string }>(); if (active) throw new Error("O veículo já possui uma reserva ativa."); const id = crypto.randomUUID(); const now = new Date().toISOString(); await db.batch([db.prepare(`INSERT INTO reservations (id, lead_id, vehicle_id, status, reserved_until, responsible, notes, created_at, updated_at) VALUES (?, ?, ?, 'ativa', ?, ?, ?, ?, ?)`).bind(id, leadId, vehicleId, text(data.reservedUntil, "Reservado até", false, 80), text(data.responsible, "Responsável", false, 200), text(data.notes, "Observações"), now, now), db.prepare(`UPDATE vehicles SET status = 'reservado', updated_at = ? WHERE id = ? AND status = 'disponivel'`).bind(now, vehicleId), db.prepare(`INSERT INTO vehicle_status_history (id, vehicle_id, from_status, to_status, changed_at, reason) VALUES (?, ?, 'disponivel', 'reservado', ?, 'Reserva comercial')`).bind(crypto.randomUUID(), vehicleId, now)]); await audit(db, request, "reservation.create", "reservation", id, { vehicleId }); return id; }
async function updateReservation(db: D1DatabaseLike, request: Request, id: string, data: CommercialData) { const current = await db.prepare(`SELECT id, vehicle_id, status FROM reservations WHERE id = ? LIMIT 1`).bind(id).first<{ id: string; vehicle_id: string; status: string }>(); if (!current) throw new Error("Reserva não encontrada."); const status = text(data.status, "Status", true); if (!status) throw new Error("Status é obrigatório."); if (!new Set(["ativa", "liberada", "convertida", "expirada", "cancelada"]).has(status)) throw new Error("Status de reserva inválido."); const now = new Date().toISOString(); await db.batch([db.prepare(`UPDATE reservations SET status = ?, reserved_until = COALESCE(?, reserved_until), responsible = COALESCE(?, responsible), notes = COALESCE(?, notes), released_at = CASE WHEN ? <> 'ativa' THEN ? ELSE released_at END, updated_at = ? WHERE id = ?`).bind(status, text(data.reservedUntil, "Reservado até", false, 80), text(data.responsible, "Responsável", false, 200), text(data.notes, "Observações"), status, now, now, id), db.prepare(`UPDATE vehicles SET status = 'disponivel', updated_at = ? WHERE id = ? AND status = 'reservado' AND ? <> 'convertida'`).bind(now, current.vehicle_id, status)]); await audit(db, request, "reservation.update", "reservation", id, { from: current.status, to: status }); }
async function createSale(db: D1DatabaseLike, request: Request, data: CommercialData) { const vehicleId = text(data.vehicleId, "Veículo", true); await vehicleExists(db, vehicleId, true); const vehicle = await db.prepare(`SELECT status FROM vehicles WHERE id = ?`).bind(vehicleId).first<{ status: string }>(); if (vehicle?.status === "vendido") throw new Error("Veículo já está vendido."); const leadId = text(data.leadId, "Lead"); await leadExists(db, leadId); const now = new Date().toISOString(); const id = crypto.randomUUID(); const previousStatus = vehicle?.status ?? "disponivel"; await db.batch([db.prepare(`INSERT INTO sales (id, lead_id, vehicle_id, customer_name, final_price_cents, down_payment_cents, trade_in_value_cents, financing_operation_id, source, responsible, sold_at, notes, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).bind(id, leadId, vehicleId, text(data.customerName, "Cliente", true), cents(data.finalPriceCents, "Preço final", true), cents(data.downPaymentCents, "Entrada") ?? 0, cents(data.tradeInValueCents, "Valor de troca") ?? 0, text(data.financingOperationId, "Financiamento"), text(data.source, "Origem", false, 100), text(data.responsible, "Responsável", false, 200), now, text(data.notes, "Observações"), now, now), db.prepare(`UPDATE vehicles SET status = 'vendido', updated_at = ? WHERE id = ?`).bind(now, vehicleId), db.prepare(`UPDATE inventory_entries SET published = 0, exit_at = ?, updated_at = ? WHERE vehicle_id = ?`).bind(now, now, vehicleId), db.prepare(`INSERT INTO vehicle_status_history (id, vehicle_id, from_status, to_status, changed_at, reason) VALUES (?, ?, ?, 'vendido', ?, 'Venda registrada')`).bind(crypto.randomUUID(), vehicleId, previousStatus, now)]); await audit(db, request, "sale.create", "sale", id, { vehicleId }); return id; }
async function createFinancing(db: D1DatabaseLike, request: Request, data: CommercialData) { const leadId = text(data.leadId, "Lead"); const vehicleId = text(data.vehicleId, "Veículo"); await leadExists(db, leadId); await vehicleExists(db, vehicleId); const term = integer(data.termMonths, "Prazo", 1, true)!; const entry = cents(data.entryCents, "Entrada") ?? 0; const rate = Number(data.ratePercent ?? 0); if (!Number.isFinite(rate) || rate < 0) throw new Error("Taxa inválida."); const id = crypto.randomUUID(); const now = new Date().toISOString(); await db.prepare(`INSERT INTO financing_operations (id, lead_id, vehicle_id, customer_name, entry_cents, term_months, rate_percent, institution, estimated_installment_cents, proposal_reference, status, notes, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).bind(id, leadId, vehicleId, text(data.customerName, "Cliente", true), entry, term, rate, text(data.institution, "Instituição", false, 200), cents(data.estimatedInstallmentCents, "Parcela estimada"), text(data.proposalReference, "Referência", false, 200), text(data.status, "Status") ?? "simulacao_interna", text(data.notes, "Observações"), now, now).run(); await audit(db, request, "financing.create", "financing", id); return id; }
async function updateFinancing(db: D1DatabaseLike, request: Request, id: string, data: CommercialData) { const mapping: Record<string, string> = { institution: "institution", estimatedInstallmentCents: "estimated_installment_cents", proposalReference: "proposal_reference", status: "status", notes: "notes" }; const valid = new Set(["simulacao_interna", "em_analise", "proposta", "aprovado", "recusado", "contratado", "cancelado"]); const sets: string[] = []; const values: unknown[] = []; for (const [key, column] of Object.entries(mapping)) if (key in data) { if (column === "status" && !valid.has(String(data[key]))) throw new Error("Status de financiamento inválido."); sets.push(`${column} = ?`); values.push(column === "estimated_installment_cents" ? cents(data[key], key) : text(data[key], key, false, 500)); } if (!sets.length) throw new Error("Nenhum campo de financiamento foi informado."); values.push(new Date().toISOString(), id); await db.prepare(`UPDATE financing_operations SET ${sets.join(", ")}, updated_at = ? WHERE id = ?`).bind(...values).run(); await audit(db, request, "financing.update", "financing", id, { fields: sets }); }

export const Route = createFileRoute("/admin/commercial/api")({ server: { handlers: {
  GET: async ({ request }) => { if (!authorized(request)) return json({ error: "Acesso administrativo não autenticado." }, 401); if (!isSameOriginRequest(request)) return json({ error: "Origem da requisição não permitida." }, 403); const db = database(); const [evaluations, negotiations, reservations, sales, financing] = await Promise.all([db.prepare(`SELECT * FROM vehicle_evaluations ORDER BY updated_at DESC LIMIT 250`).all(), db.prepare(`SELECT n.*, v.brand, v.model FROM negotiations n LEFT JOIN vehicles v ON v.id = n.vehicle_id ORDER BY n.updated_at DESC LIMIT 250`).all(), db.prepare(`SELECT r.*, v.brand, v.model FROM reservations r LEFT JOIN vehicles v ON v.id = r.vehicle_id ORDER BY r.updated_at DESC LIMIT 250`).all(), db.prepare(`SELECT s.*, v.brand, v.model FROM sales s LEFT JOIN vehicles v ON v.id = s.vehicle_id ORDER BY s.sold_at DESC LIMIT 250`).all(), db.prepare(`SELECT f.*, v.brand, v.model FROM financing_operations f LEFT JOIN vehicles v ON v.id = f.vehicle_id ORDER BY f.updated_at DESC LIMIT 250`).all()]); return json({ evaluations: evaluations.results ?? [], negotiations: negotiations.results ?? [], reservations: reservations.results ?? [], sales: sales.results ?? [], financing: financing.results ?? [] }); },
  POST: async ({ request }) => { if (!authorized(request)) return json({ error: "Acesso administrativo não autenticado." }, 401); if (!isSameOriginRequest(request)) return json({ error: "Origem da requisição não permitida." }, 403); if (!hasAcceptableJsonContentType(request)) return json({ error: "Content-Type inválido." }, 415); if (exceedsBodyLimit(request)) return json({ error: "Payload administrativo excede o limite permitido." }, 413); try { const input = await request.json() as Action; const db = database(); let id: string | null = null; switch (input.action) { case "evaluation.create": id = await createEvaluation(db, request, input.data); break; case "evaluation.update": await updateEvaluation(db, request, input.id, input.data); id = input.id; break; case "negotiation.create": id = await createNegotiation(db, request, input.data); break; case "negotiation.update": await updateNegotiation(db, request, input.id, input.data); id = input.id; break; case "reservation.create": id = await createReservation(db, request, input.data); break; case "reservation.update": await updateReservation(db, request, input.id, input.data); id = input.id; break; case "sale.create": id = await createSale(db, request, input.data); break; case "financing.create": id = await createFinancing(db, request, input.data); break; case "financing.update": await updateFinancing(db, request, input.id, input.data); id = input.id; break; default: throw new Error("Operação comercial inválida."); } return json({ ok: true, id }); } catch (error) { return json({ error: error instanceof Error ? error.message : "Operação não concluída." }, 400); } },
} } });