import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, RefreshCw } from "lucide-react";
import { Link, createFileRoute } from "@tanstack/react-router";

type Row = { id?: unknown; [key: string]: unknown };
type Data = { evaluations: Row[]; negotiations: Row[]; reservations: Row[]; sales: Row[]; financing: Row[] };
const labels: Record<string, string> = { pendente: "Pendente", aprovada: "Aprovada", recusada: "Recusada", convertida: "Convertida", aberta: "Aberta", proposta: "Proposta", contraproposta: "Contraproposta", fechada: "Fechada", perdida: "Perdida", ativa: "Ativa", liberada: "Liberada", expirada: "Expirada", cancelada: "Cancelada", simulacao_interna: "Simulação interna", em_analise: "Em análise", aprovado: "Aprovado", recusado: "Recusado", contratado: "Contratado", cancelado: "Cancelado" };
const money = (value: unknown) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value ?? 0) / 100);

export const Route = createFileRoute("/admin/operacao")({ component: OperationPage });

function OperationPage() {
  const [data, setData] = useState<Data | null>(null); const [tab, setTab] = useState("avaliacoes"); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  const load = async () => { setLoading(true); try { const response = await fetch("/admin/commercial/api", { headers: { Accept: "application/json" } }); const result = await response.json() as Data & { error?: string }; if (!response.ok) throw new Error(result.error ?? "Falha ao carregar a operação."); setData(result); } catch (error) { setMessage(error instanceof Error ? error.message : "Falha ao carregar a operação."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const counts = useMemo(() => ({ avaliacoes: data?.evaluations.length ?? 0, negociacoes: data?.negotiations.length ?? 0, reservas: data?.reservations.length ?? 0, vendas: data?.sales.length ?? 0, financiamento: data?.financing.length ?? 0 }), [data]);
  const tabs = [["avaliacoes", "Avaliações"], ["negociacoes", "Negociações"], ["reservas", "Reservas"], ["vendas", "Vendas"], ["financiamento", "Financiamento"]] as const;
  return <main className="min-h-[calc(100vh-120px)] bg-background"><div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-gold">Operação comercial</p><h1 className="mt-1 text-3xl font-bold">Central de operação</h1><p className="mt-2 text-sm text-muted-foreground">Avaliações, negociações, reservas, vendas e financiamento real.</p></div><div className="flex gap-2"><button onClick={() => void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-sm border border-border px-4 py-2.5 text-sm font-semibold hover:bg-accent"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />Atualizar</button><Link to="/admin/crm" className="inline-flex items-center gap-2 rounded-sm border border-border px-4 py-2.5 text-sm font-semibold hover:bg-accent"><ArrowLeft className="h-4 w-4" />CRM</Link></div></div>{message && <div className="mt-5 rounded-sm border border-border bg-card px-4 py-3 text-sm">{message}</div>}<div className="mt-6 grid gap-2 sm:grid-cols-5">{tabs.map(([key, label]) => <button key={key} onClick={() => setTab(key)} className={`rounded-sm border px-3 py-3 text-left text-sm font-semibold ${tab === key ? "border-gold bg-secondary" : "border-border bg-card hover:bg-accent"}`}><span>{label}</span><span className="ml-2 text-muted-foreground">{counts[key]}</span></button>)}</div><section className="mt-5 rounded-sm border border-border bg-card p-5">{loading && !data ? <div className="py-16 text-center text-sm text-muted-foreground">Carregando operação…</div> : tab === "avaliacoes" ? <Evaluations rows={data?.evaluations ?? []} /> : tab === "negociacoes" ? <Negotiations rows={data?.negotiations ?? []} /> : tab === "reservas" ? <Reservations rows={data?.reservations ?? []} /> : tab === "vendas" ? <Sales rows={data?.sales ?? []} /> : <Financing rows={data?.financing ?? []} />}</section></div></main>;
}
function Empty() { return <div className="py-12 text-center text-sm text-muted-foreground">Nenhum registro encontrado.</div>; }
function Evaluations({ rows }: { rows: Row[] }) { return <Table title="Avaliações de veículos" columns={[["customer_name", "Cliente"], ["vehicle_description", "Veículo"], ["decision", "Decisão"], ["evaluated_value_cents", "Valor avaliado"]]} rows={rows} />; }
function Negotiations({ rows }: { rows: Row[] }) { return <Table title="Negociações" columns={[["customer_name", "Cliente"], ["brand", "Veículo"], ["stage", "Etapa"], ["proposed_price_cents", "Preço proposto"]]} rows={rows} />; }
function Reservations({ rows }: { rows: Row[] }) { return <Table title="Reservas" columns={[["customer_name", "Cliente"], ["brand", "Veículo"], ["status", "Status"], ["reserved_until", "Reservado até"]]} rows={rows} />; }
function Sales({ rows }: { rows: Row[] }) { return <Table title="Vendas" columns={[["customer_name", "Cliente"], ["brand", "Veículo"], ["final_price_cents", "Valor final"], ["sold_at", "Data"]]} rows={rows} />; }
function Financing({ rows }: { rows: Row[] }) { return <Table title="Operações de financiamento" columns={[["customer_name", "Cliente"], ["brand", "Veículo"], ["status", "Status"], ["term_months", "Prazo"], ["estimated_installment_cents", "Parcela"]]} rows={rows} />; }
function Table({ title, columns, rows }: { title: string; columns: [string, string][]; rows: Row[] }) { return <div><div className="flex items-center justify-between"><h2 className="text-lg font-bold">{title}</h2><span className="text-xs text-muted-foreground">{rows.length} registro(s)</span></div>{rows.length === 0 ? <Empty /> : <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-border text-xs uppercase tracking-wider text-muted-foreground"><tr>{columns.map(([, label]) => <th key={label} className="pb-3 pr-5">{label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={String(row.id ?? index)} className="border-b border-border/70"><td className="py-3 pr-5 font-semibold">{String(row[columns[0][0]] ?? "—")}</td>{columns.slice(1).map(([key]) => <td key={key} className="py-3 pr-5 text-muted-foreground">{key.endsWith("_cents") ? money(row[key]) : key === "decision" || key === "stage" || key === "status" ? labels[String(row[key])] ?? String(row[key] ?? "—") : key.endsWith("_at") ? new Date(String(row[key])).toLocaleString("pt-BR") : String(row[key] ?? "—")}</td>)}</tr>)}</tbody></table></div>}</div>; }
