/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as EstoqueIdRouteImport } from './routes/estoque_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueIdRoute = EstoqueIdRouteImport.update({
  id: '/estoque/$id',
  path: '/estoque/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/estoque': typeof EstoqueRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/estoque/$id': typeof EstoqueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/estoque': typeof EstoqueRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/estoque/$id': typeof EstoqueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/estoque': typeof EstoqueRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/estoque/$id': typeof EstoqueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/estoque'
    | '/servicos'
    | '/sobre'
    | '/estoque/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/estoque'
    | '/servicos'
    | '/sobre'
    | '/estoque/$id'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/estoque'
    | '/servicos'
    | '/sobre'
    | '/estoque/$id'
  fileRoutesById: FileRoutesById
}

interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  EstoqueRoute: typeof EstoqueRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
  EstoqueIdRoute: typeof EstoqueIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  EstoqueRoute: EstoqueRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
  EstoqueIdRoute: EstoqueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
